### PR TITLE
Added in No-opinion button and tests

### LINKED ISSUE #19: "no-opinion" button
@romusc suggests we could have a "no-opinion" button

### PR DESCRIPTION
**Pull request by Zsuark**
Implemented with tests as per https://github.com/AgileVentures/asyncvoter-slack-command/issues/19

Closes #19

### CODE REVIEW

**Comment by tansaku** [comment]
this looks good - in the absence of CI and CodeClimate I'd love to deploy to azure and test it all works before a final deploy - but maybe it can just go to staging ...

**Comment by Zsuark** [comment]
This is complete - but I think we need to discuss if it is really needed before we merge it.

After all, it is someone abstaining from voting. Why not just simply not vote - it may also mean that it looks like more people have voted when in fact they've just abstained.

**Comment by tansaku** [comment]
I guess the argument is that the "no-vote" makes for less pressure on someone to make a specific vote, i.e. not just guess randomly

We just had one person request it - maybe adding it is knee-jerk ...

**Comment by tansaku** [comment]
I can form arguments for and against it ... seems something like we can try and see how people react ...

**Comment by Zsuark** [comment]
Maybe we can have an abstain list, with no votes for that person counting (deleted) and the abstain list is also presented at the end.

**Comment by mattlindsey** [comment]
@tansaku and @Zsuark What's the status of this PR?  
Should we put into staging with the other 2 open PRs?  #24 and #26

**Comment by Zsuark** [comment]
@mattlindsey I'm not sure. I have no opinion on this feature - I just completed it because it was in the ready queue.

**Pull request merged**
