### PR TITLE
# 30 add initial working /voter --help command [WIP]

### PR DESCRIPTION
**Pull request by vardyb**
Add instructions on how to use /voter command when user enters `/voter --help`

### CODE REVIEW

**Comment by vardyb** [comment]
First version with working `/voter --help`.

Need to agree on text to display and also look to write tests.

Thanks to @nimitbhargava for his help in the Pairing session.

**Comment by tansaku** [comment]
Some ideas for the help message:

```AsyncVoter allows you and your slack team to run "planning poker" style votes on stories or issues relating to your project.  The idea is that everyone can vote in secret and then all votes are revealed at once to expose differences in assumptions and facilitate discussion

/voter can take any text argument - we recommend that you describe the title of the issue you are planning to vote on, and then a URL to a permanent linked ticket where the results of the vote can be stored.

Any number of votes can be started in a channel and run independently. Anyone in the channel can register their vote through the interface that will pop up when a vote is started, voting Simple(1), Medium(2) or Hard(3) based on how difficult they think it will be to complete work on the issue.  Undecided folks can vote "No Opinion" and when everyone is ready, anyone can press reveal to reveal who voted want.

Voting is no substitute for discussion.  Really it's all about communicating with your team and agreeing to compromise when it's time to move on```

**Comment by vardyb** [comment]
@tansaku check out the latest commits - this adds full help text based on your comment earlier today.  Activation now works using `/voter --help` and `/voter help`.

**Comment by tansaku** [comment]
great work @vardyb ! :-)

**Pull request merged**
